spring:
  application:
    name: cinevibe
  datasource:
    url: jdbc:postgresql://localhost:5432/cine_vibe
    password: password
    username: postgres
jwt:
    expireTime: 900000
    secretKey: cJrXVTptebaGAZXbo5+BBwNufO1oPQl2BOuHdQYmfOQ=
