spring:
  application:
    name: cinevibe
  datasource:
    url: jdbc:postgresql://localhost:5432/cine_vibe
    password: password
    username: postgres
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
    expireTime: 900000
    secretKey: cJrXVTptebaGAZXbo5+BBwNufO1oPQl2BOuHdQYmfOQ=

cloudinary:
  cloud:
    name:
  api:
    key:
    secret:

